---
version: "3"

services:
  nginx:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/letsencrypt
      - sites-availables:/etc/nginx/conf.d

volumes:
  certs:
    name: certs
  sites-availables:
    name: sites-availables
