---
version: "3.7"

services:
  nginx:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt/
      - sites-availables:/etc/nginx/conf.d/
    networks:
      - selfhost

volumes:
  sites-availables:
    name: sites-availables
  certs:
    name: certs

networks:
  selfhost:
    name: selfhost
